---
- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX | Updating apt cache
  apt:
    update_cache: yes

- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

- name: Copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration
  template: src=buildpay_webapp dest=/etc/nginx/sites-available/buildpay_webapp

- name: Remove default nginx conf file
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable nginx config
  file: src={{ item.path }} dest={{ item.dest }} state=link
  with_items:
    - { path: '/etc/nginx/sites-available/buildpay_webapp', dest: '/etc/nginx/sites-enabled/buildpay_webapp' }
  notify: restart nginx

